/**
 * TrainedBy  -  Content Agent
 * ─────────────────────────────────────────────────────────────────────────────
 * Triggered by: pg_cron every Monday at 08:00 (per market timezone)
 *
 * What it does:
 *   For each active Pro trainer:
 *   1. Generates 3 Instagram caption ideas tailored to their specialties,
 *      city, and current market context (season, local events, trending topics)
 *   2. Sends them via the trainer's preferred channel
 *
 * The trainer reads it on Monday morning, picks one, posts it.
 * Zero effort on their part.
 */

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { createLogger } from '../_shared/logger.ts';
import { sendToTrainer } from '../_shared/channel.ts';
import { getMarket, getPersona, type Locale } from '../_shared/locale.ts';

const log = createLogger('agent-content');

const ANTHROPIC_KEY = () => Deno.env.get('ANTHROPIC_API_KEY')!;

async function generateCaptions(
  trainerName: string,
  specialties: string[],
  market: ReturnType<typeof getMarket>,
  persona: string,
): Promise<string[]> {
  const month = new Date().toLocaleString('en', { month: 'long' });

  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'x-api-key': ANTHROPIC_KEY(),
      'anthropic-version': '2023-06-01',
      'content-type': 'application/json',
    },
    body: JSON.stringify({
      model: 'claude-haiku-4-5',
      max_tokens: 600,
      temperature: 0.8,
      system: `${persona} You write Instagram captions for personal trainers. Each caption: 3-5 sentences, ends with a CTA or question, includes 5-8 relevant hashtags. Vary the angles: one educational, one motivational, one personal/story-based. Write in ${market.language}. Sound like a real trainer, not a brand account.`,
      messages: [{
        role: 'user',
        content: `Trainer: ${trainerName}. Specialties: ${specialties.join(', ') || 'general fitness'}. City: ${market.city}. Month: ${month}. Local context: ${market.localContext.slice(0, 3).join(', ')}.

Generate exactly 3 Instagram captions. Format:
CAPTION 1:
[caption text + hashtags]

CAPTION 2:
[caption text + hashtags]

CAPTION 3:
[caption text + hashtags]`,
      }],
    }),
  });

  const data = await res.json();
  const raw = data.content?.[0]?.text ?? '';

  // Parse the 3 captions
  const captions = raw
    .split(/CAPTION \d+:/i)
    .map((s: string) => s.trim())
    .filter((s: string) => s.length > 20);

  return captions.slice(0, 3);
}

Deno.serve(async (_req: Request) => {
  const sb = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
  );

  // Fetch all active Pro trainers
  const { data: trainers } = await sb
    .from('trainers')
    .select('id, name, full_name, specialties, locale, plan, assistant_channel, telegram_chat_id, whatsapp')
    .in('plan', ['pro', 'premium'])
    .not('assistant_channel', 'is', null)
    .limit(500);

  if (!trainers?.length) {
    log.info('No Pro trainers found');
    return new Response(JSON.stringify({ ok: true, sent: 0 }), { status: 200 });
  }

  let sent = 0;
  for (const trainer of trainers) {
    const market = getMarket(trainer.locale as Locale);
    const persona = getPersona(trainer.locale as Locale);
    const trainerName = trainer.name || trainer.full_name || 'Trainer';
    const specialties = Array.isArray(trainer.specialties) ? trainer.specialties : [];

    try {
      const captions = await generateCaptions(trainerName, specialties, market, persona);

      const numbered = captions.map((c, i) => `*Option ${i + 1}:*\n${c}`).join('\n\n─────────────────\n\n');

      const message = [
        `📱 *Your content ideas for this week*`,
        `Pick one, post it today. Or save them for later.`,
        '',
        numbered,
        '',
        `_Generated by your Content Agent every Monday._`,
      ].join('\n');

      await sendToTrainer(
        {
          channel: trainer.assistant_channel || 'dashboard',
          telegram_chat_id: trainer.telegram_chat_id,
          whatsapp: trainer.whatsapp,
          trainer_id: trainer.id,
        },
        { text: message },
        'content-agent',
      );

      sent++;
      // Stagger sends to avoid rate limits
      await new Promise(r => setTimeout(r, 300));
    } catch (err) {
      log.error('Failed to send content to trainer', { trainer_id: trainer.id, err });
    }
  }

  log.info('Content agent done', { sent });
  return new Response(JSON.stringify({ ok: true, sent }), { status: 200 });
});
